### ISSUE TITLE
Inconsistency between log_q and log_p in Encoder and NormalizingFlowVAE

### ISSUE THREAD

**Issue by maulberto3** [VincentStimper/normalizing-flows#16]
In NormalizingFlowVAE class in core.py, this [line](https://github.com/VincentStimper/normalizing-flows/blob/bbcd6c11be997ad7a0ca4da43592f2a6b9d7d878/normflows/core.py#L418) says that the encoder outputs _log_q_:

`z, log_q = self.q0(x, num_samples=num_samples)`

Suppose that, as in [this](https://github.com/VincentStimper/normalizing-flows/blob/master/example/vae.ipynb) example, the encoder Gaussian (_q0_) is parameterized by an MLP. Looking at distributions.encoder.py source code, the forward method of NNDiagGaussian class says that it outputs _log_p_:

`return z, log_p`

Inconsistency or not?

**Comment by VincentStimper** [comment]
Hi @maulberto3,

Sorry for the late reply. I'll go through the other issues you raised as well in the next days.
First of all, the name for the log probability does not affect the behavior of the code, so even though there is an inconsistency, the code should still work as expected.
Whether you denote the density by `p` or `q` depends on what you use it for. Since the Encoder is primarily meant to be used in variational inference here, I agree that consistently calling it `log_q` seems more reasonable since the encoder is typically the distribution to be inferred.
I changed the name in my [development branch](https://github.com/VincentStimper/normalizing-flows/tree/dev-vs) and will merge this to `master` together with some other changes soon.
I'm closing this issue, but you are welcome to reopen it if there is still something unclear.

Best regards,
Vincent
