### ISSUE TITLE
RuntimeError: output with shape [32] doesn't match the broadcast shape [1, 32]

### ISSUE THREAD

**Issue by maulberto3** [VincentStimper/normalizing-flows#19]
Hi, when doing experiments, I'd suggest doing some other tutorials, for example for the ClassCondFlow, as while trying to one on my own, I keep encountering this error.

**Comment by VincentStimper** [comment]
Hi @maulberto3,

if you still encounter this issue, feel free to reopen this issue and please provide more details, ideally your entire code.

Best regards,
Vincent

**Comment by VincentStimper** [comment]
Hi @maulberto3,

when adding tests to the VAE model, I realized that the behavior of the [`NNBernoulliDecoder`](https://github.com/VincentStimper/normalizing-flows/blob/master/normflows/distributions/decoder.py#L73) and the [`NNDiagGaussianDecoder`](https://github.com/VincentStimper/normalizing-flows/blob/master/normflows/distributions/decoder.py#L34) is different. We used them in different contexts before, which is why only the former worked with the [`NormalizingFlowVAE`](https://github.com/VincentStimper/normalizing-flows/blob/master/normflows/core.py#L448) module, but the latter caused an error. 
I fix this now such that the [`NormalizingFlowVAE`](https://github.com/VincentStimper/normalizing-flows/blob/master/normflows/core.py#L448) works with both decoders. Apologies for the inconveniences this might have caused.

Best regards,
Vincent
